/*
 * generated by Xtext 2.32.0.M3
 */
package org.xtext.example.mydsl;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class RDFTurtleStandaloneSetup extends RDFTurtleStandaloneSetupGenerated {

	public static void doSetup() {
		new RDFTurtleStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
