/*
 * generated by Xtext 2.32.0.M3
 */
package org.xtext.example.mydsl;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class RDFTurtleRuntimeModule extends AbstractRDFTurtleRuntimeModule {
}
