/**
 * generated by Xtext 2.32.0.M3
 */
package org.xtext.example.mydsl.rDFTurtle;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Directive</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.rDFTurtle.Directive#getPrefix <em>Prefix</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.rDFTurtle.Directive#getBase <em>Base</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.rDFTurtle.Directive#getSparqlPrefix <em>Sparql Prefix</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.rDFTurtle.Directive#getSparqlBase <em>Sparql Base</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.rDFTurtle.RDFTurtlePackage#getDirective()
 * @model
 * @generated
 */
public interface Directive extends EObject
{
  /**
   * Returns the value of the '<em><b>Prefix</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Prefix</em>' containment reference.
   * @see #setPrefix(PrefixID)
   * @see org.xtext.example.mydsl.rDFTurtle.RDFTurtlePackage#getDirective_Prefix()
   * @model containment="true"
   * @generated
   */
  PrefixID getPrefix();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.rDFTurtle.Directive#getPrefix <em>Prefix</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Prefix</em>' containment reference.
   * @see #getPrefix()
   * @generated
   */
  void setPrefix(PrefixID value);

  /**
   * Returns the value of the '<em><b>Base</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Base</em>' containment reference.
   * @see #setBase(Base)
   * @see org.xtext.example.mydsl.rDFTurtle.RDFTurtlePackage#getDirective_Base()
   * @model containment="true"
   * @generated
   */
  Base getBase();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.rDFTurtle.Directive#getBase <em>Base</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Base</em>' containment reference.
   * @see #getBase()
   * @generated
   */
  void setBase(Base value);

  /**
   * Returns the value of the '<em><b>Sparql Prefix</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Sparql Prefix</em>' containment reference.
   * @see #setSparqlPrefix(SparqlPrefix)
   * @see org.xtext.example.mydsl.rDFTurtle.RDFTurtlePackage#getDirective_SparqlPrefix()
   * @model containment="true"
   * @generated
   */
  SparqlPrefix getSparqlPrefix();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.rDFTurtle.Directive#getSparqlPrefix <em>Sparql Prefix</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Sparql Prefix</em>' containment reference.
   * @see #getSparqlPrefix()
   * @generated
   */
  void setSparqlPrefix(SparqlPrefix value);

  /**
   * Returns the value of the '<em><b>Sparql Base</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Sparql Base</em>' containment reference.
   * @see #setSparqlBase(SparqlBase)
   * @see org.xtext.example.mydsl.rDFTurtle.RDFTurtlePackage#getDirective_SparqlBase()
   * @model containment="true"
   * @generated
   */
  SparqlBase getSparqlBase();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.rDFTurtle.Directive#getSparqlBase <em>Sparql Base</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Sparql Base</em>' containment reference.
   * @see #getSparqlBase()
   * @generated
   */
  void setSparqlBase(SparqlBase value);

} // Directive
