/**
 * generated by Xtext 2.33.0
 */
package org.xtext.example.mydsl.rDFTurtle;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>iResource</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.rDFTurtle.iResource#getIriRef <em>Iri Ref</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.rDFTurtle.iResource#getQname <em>Qname</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.rDFTurtle.RDFTurtlePackage#getiResource()
 * @model
 * @generated
 */
public interface iResource extends EObject
{
  /**
   * Returns the value of the '<em><b>Iri Ref</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Iri Ref</em>' attribute.
   * @see #setIriRef(String)
   * @see org.xtext.example.mydsl.rDFTurtle.RDFTurtlePackage#getiResource_IriRef()
   * @model
   * @generated
   */
  String getIriRef();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.rDFTurtle.iResource#getIriRef <em>Iri Ref</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Iri Ref</em>' attribute.
   * @see #getIriRef()
   * @generated
   */
  void setIriRef(String value);

  /**
   * Returns the value of the '<em><b>Qname</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Qname</em>' containment reference.
   * @see #setQname(Qname)
   * @see org.xtext.example.mydsl.rDFTurtle.RDFTurtlePackage#getiResource_Qname()
   * @model containment="true"
   * @generated
   */
  Qname getQname();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.rDFTurtle.iResource#getQname <em>Qname</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Qname</em>' containment reference.
   * @see #getQname()
   * @generated
   */
  void setQname(Qname value);

} // iResource
