/**
 * generated by Xtext 2.32.0
 */
package org.xtext.example.mydsl.rDFTurtle;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Predicate Object List</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.rDFTurtle.PredicateObjectList#getPredicateObjects <em>Predicate Objects</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.rDFTurtle.RDFTurtlePackage#getPredicateObjectList()
 * @model
 * @generated
 */
public interface PredicateObjectList extends EObject
{
  /**
   * Returns the value of the '<em><b>Predicate Objects</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.rDFTurtle.PredicateObject}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Predicate Objects</em>' containment reference list.
   * @see org.xtext.example.mydsl.rDFTurtle.RDFTurtlePackage#getPredicateObjectList_PredicateObjects()
   * @model containment="true"
   * @generated
   */
  EList<PredicateObject> getPredicateObjects();

} // PredicateObjectList
