/**
 * generated by Xtext 2.33.0
 */
package org.xtext.example.mydsl.rDFTurtle;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Verb</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.rDFTurtle.Verb#getPredicate <em>Predicate</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.rDFTurtle.Verb#isIsA <em>Is A</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.rDFTurtle.RDFTurtlePackage#getVerb()
 * @model
 * @generated
 */
public interface Verb extends EObject
{
  /**
   * Returns the value of the '<em><b>Predicate</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Predicate</em>' containment reference.
   * @see #setPredicate(iResource)
   * @see org.xtext.example.mydsl.rDFTurtle.RDFTurtlePackage#getVerb_Predicate()
   * @model containment="true"
   * @generated
   */
  iResource getPredicate();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.rDFTurtle.Verb#getPredicate <em>Predicate</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Predicate</em>' containment reference.
   * @see #getPredicate()
   * @generated
   */
  void setPredicate(iResource value);

  /**
   * Returns the value of the '<em><b>Is A</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Is A</em>' attribute.
   * @see #setIsA(boolean)
   * @see org.xtext.example.mydsl.rDFTurtle.RDFTurtlePackage#getVerb_IsA()
   * @model
   * @generated
   */
  boolean isIsA();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.rDFTurtle.Verb#isIsA <em>Is A</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Is A</em>' attribute.
   * @see #isIsA()
   * @generated
   */
  void setIsA(boolean value);

} // Verb
