/**
 * generated by Xtext 2.33.0
 */
package org.xtext.example.mydsl.rDFTurtle.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.mydsl.rDFTurtle.Qname;
import org.xtext.example.mydsl.rDFTurtle.RDFTurtlePackage;
import org.xtext.example.mydsl.rDFTurtle.iResource;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>iResource</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.rDFTurtle.impl.iResourceImpl#getIr <em>Ir</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.rDFTurtle.impl.iResourceImpl#getIriRef <em>Iri Ref</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.rDFTurtle.impl.iResourceImpl#getQname <em>Qname</em>}</li>
 * </ul>
 *
 * @generated
 */
public class iResourceImpl extends MinimalEObjectImpl.Container implements iResource
{
  /**
   * The cached value of the '{@link #getIr() <em>Ir</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getIr()
   * @generated
   * @ordered
   */
  protected iResource ir;

  /**
   * The default value of the '{@link #getIriRef() <em>Iri Ref</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getIriRef()
   * @generated
   * @ordered
   */
  protected static final String IRI_REF_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getIriRef() <em>Iri Ref</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getIriRef()
   * @generated
   * @ordered
   */
  protected String iriRef = IRI_REF_EDEFAULT;

  /**
   * The cached value of the '{@link #getQname() <em>Qname</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getQname()
   * @generated
   * @ordered
   */
  protected Qname qname;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected iResourceImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return RDFTurtlePackage.Literals.IRESOURCE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public iResource getIr()
  {
    return ir;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetIr(iResource newIr, NotificationChain msgs)
  {
    iResource oldIr = ir;
    ir = newIr;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, RDFTurtlePackage.IRESOURCE__IR, oldIr, newIr);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setIr(iResource newIr)
  {
    if (newIr != ir)
    {
      NotificationChain msgs = null;
      if (ir != null)
        msgs = ((InternalEObject)ir).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - RDFTurtlePackage.IRESOURCE__IR, null, msgs);
      if (newIr != null)
        msgs = ((InternalEObject)newIr).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - RDFTurtlePackage.IRESOURCE__IR, null, msgs);
      msgs = basicSetIr(newIr, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, RDFTurtlePackage.IRESOURCE__IR, newIr, newIr));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getIriRef()
  {
    return iriRef;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setIriRef(String newIriRef)
  {
    String oldIriRef = iriRef;
    iriRef = newIriRef;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, RDFTurtlePackage.IRESOURCE__IRI_REF, oldIriRef, iriRef));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Qname getQname()
  {
    return qname;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetQname(Qname newQname, NotificationChain msgs)
  {
    Qname oldQname = qname;
    qname = newQname;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, RDFTurtlePackage.IRESOURCE__QNAME, oldQname, newQname);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setQname(Qname newQname)
  {
    if (newQname != qname)
    {
      NotificationChain msgs = null;
      if (qname != null)
        msgs = ((InternalEObject)qname).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - RDFTurtlePackage.IRESOURCE__QNAME, null, msgs);
      if (newQname != null)
        msgs = ((InternalEObject)newQname).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - RDFTurtlePackage.IRESOURCE__QNAME, null, msgs);
      msgs = basicSetQname(newQname, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, RDFTurtlePackage.IRESOURCE__QNAME, newQname, newQname));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case RDFTurtlePackage.IRESOURCE__IR:
        return basicSetIr(null, msgs);
      case RDFTurtlePackage.IRESOURCE__QNAME:
        return basicSetQname(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case RDFTurtlePackage.IRESOURCE__IR:
        return getIr();
      case RDFTurtlePackage.IRESOURCE__IRI_REF:
        return getIriRef();
      case RDFTurtlePackage.IRESOURCE__QNAME:
        return getQname();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case RDFTurtlePackage.IRESOURCE__IR:
        setIr((iResource)newValue);
        return;
      case RDFTurtlePackage.IRESOURCE__IRI_REF:
        setIriRef((String)newValue);
        return;
      case RDFTurtlePackage.IRESOURCE__QNAME:
        setQname((Qname)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case RDFTurtlePackage.IRESOURCE__IR:
        setIr((iResource)null);
        return;
      case RDFTurtlePackage.IRESOURCE__IRI_REF:
        setIriRef(IRI_REF_EDEFAULT);
        return;
      case RDFTurtlePackage.IRESOURCE__QNAME:
        setQname((Qname)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case RDFTurtlePackage.IRESOURCE__IR:
        return ir != null;
      case RDFTurtlePackage.IRESOURCE__IRI_REF:
        return IRI_REF_EDEFAULT == null ? iriRef != null : !IRI_REF_EDEFAULT.equals(iriRef);
      case RDFTurtlePackage.IRESOURCE__QNAME:
        return qname != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (iriRef: ");
    result.append(iriRef);
    result.append(')');
    return result.toString();
  }

} //iResourceImpl
