/*
 * generated by Xtext 2.32.0.M3
 */
package org.xtext.example.mydsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class RDFTurtleUiModule extends AbstractRDFTurtleUiModule {

	public RDFTurtleUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
