/*
 * generated by Xtext 2.32.0.M3
 */
package org.xtext.example.mydsl.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.example.mydsl.parser.antlr.internal.InternalRDFTurtleParser;
import org.xtext.example.mydsl.services.RDFTurtleGrammarAccess;

public class RDFTurtleParser extends AbstractAntlrParser {

	@Inject
	private RDFTurtleGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalRDFTurtleParser createParser(XtextTokenStream stream) {
		return new InternalRDFTurtleParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "TurtleDoc";
	}

	public RDFTurtleGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(RDFTurtleGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
